name: campus_app
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  file_picker: ^5.2.10
  cloud_firestore: ^4.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  fl_chart: ^0.68.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  open_file: ^3.3.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^10.0.1
  timeago: ^3.1.0
  uuid: ^4.4.2
  firebase_auth: ^4.16.0
  url_launcher: ^6.1.7
  firebase_storage: ^11.2.1
  envied: ^0.5.4+1
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.11  # Downgraded to be compatible with Dart SDK 3.4.4
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/community4.webp
    - assets/images/community3.webp
    - assets/images/communityPicture.webp
    - assets/images/community2Picture.webp
    - assets/images/profile-pic.png
    - assets/images/comment.png
    - assets/images/like.png
    - assets/images/announcement.png
    - assets/images/bell.png
    - assets/images/party-hat.png
    - assets/images/liked-a-comment.png
    - assets/images/friends.png
    - assets/images/events.jpg
    - assets/images/officess.png
    - assets/images/posts.png
    - assets/images/ahmed.jpg
    - assets/images/anas.jpg
    - assets/images/hussien.jpg
    - assets/images/ibrahim.jpg
    - assets/images/mohanad.jpg
    - assets/images/outlets.png
    - .env
