// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwt6XiHvlk46DtZXwrl6c4NPXfnw708o',
    appId: '1:709052786972:web:ed7d94965cc1e8b1ef32d9',
    messagingSenderId: '709052786972',
    projectId: 'campus-app-d0e52',
    authDomain: 'campus-app-d0e52.firebaseapp.com',
    databaseURL: 'https://campus-app-d0e52-default-rtdb.firebaseio.com',
    storageBucket: 'campus-app-d0e52.appspot.com',
    measurementId: 'G-G81QMC0GV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjSTrqtODDsBODurZNyUTo0SSF7jEwfY4',
    appId: '1:709052786972:android:459bbbae704376a3ef32d9',
    messagingSenderId: '709052786972',
    projectId: 'campus-app-d0e52',
    databaseURL: 'https://campus-app-d0e52-default-rtdb.firebaseio.com',
    storageBucket: 'campus-app-d0e52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjUAG7Wbhf7YM92WLzjqu5s5VKZlHPw4',
    appId: '1:709052786972:ios:89bd58041d24e5b9ef32d9',
    messagingSenderId: '709052786972',
    projectId: 'campus-app-d0e52',
    databaseURL: 'https://campus-app-d0e52-default-rtdb.firebaseio.com',
    storageBucket: 'campus-app-d0e52.appspot.com',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjUAG7Wbhf7YM92WLzjqu5s5VKZlHPw4',
    appId: '1:709052786972:ios:89bd58041d24e5b9ef32d9',
    messagingSenderId: '709052786972',
    projectId: 'campus-app-d0e52',
    databaseURL: 'https://campus-app-d0e52-default-rtdb.firebaseio.com',
    storageBucket: 'campus-app-d0e52.appspot.com',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdwt6XiHvlk46DtZXwrl6c4NPXfnw708o',
    appId: '1:709052786972:web:af8ddea0272df4e0ef32d9',
    messagingSenderId: '709052786972',
    projectId: 'campus-app-d0e52',
    authDomain: 'campus-app-d0e52.firebaseapp.com',
    databaseURL: 'https://campus-app-d0e52-default-rtdb.firebaseio.com',
    storageBucket: 'campus-app-d0e52.appspot.com',
    measurementId: 'G-SDR2E8LC22',
  );
}
